default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3

test:
  primary:
    <<: *default
    database: db/test.sqlite3

production:
  primary:
    <<: *default
    database: db/production.sqlite3